# ArbotiX simulator configuration for Limo Ackerman Robot

controllers: {
  base_controller: {
    type: diff_controller,
    base_frame_id: base_footprint,
    odom_frame_id: odom,
    base_width: 0.14,  # track is 0.14m
    ticks_meter: 1000,
    joints: [rear_left_wheel, rear_right_wheel]
  }
}
